openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Unqueue CSF Delivery API'
  description: 'API documentation for Unqueue X CSF API'
servers:
  - url: https://api-orjbtud76q-uc.a.run.app/v1
    description: Main (production) server
  - url: https://api-ctzzdgmeyq-uc.a.run.app/v1
    description: Internal staging server for testing

paths:
  /orders/onboard:
    post:
      summary: Collect an order from warehouse to complete customer delivery.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - deviceId
              properties:
                orderId:
                  type: string
                  description: ID of the order to onboard.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/offload:
    post:
      summary: Unload orders back into the warehouse.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - deviceId
              properties:
                orderId:
                  type: string
                  description: ID of the order to offload.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/merchant-pickup:
    post:
      summary: Collect orders from a merchant.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - deviceId
              properties:
                orderId:
                  type: string
                  description: ID of the order to pick up.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/customer-pickup:
    post:
      summary: Collect package from customer to complete return request.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - deviceId
              properties:
                orderId:
                  type: string
                  description: ID of the order for return pick up.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/hold:
    post:
      summary: Put an international order on hold.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - deviceId
                - orderId
                - date
                - customerId
                - holdId
                - invoiceId
                - holdProof
                - rescheduleDate
                - note
              properties:
                orderId:
                  type: string
                  description: ID of the order for return pick up.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
                date:
                  type: string
                customerId:
                  type: string
                holdId:
                  type: string
                invoiceId:
                  type: string
                holdProof:
                  type: string
                rescheduleDate:
                  type: string
                note:
                  type: string
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/deliver:
    post:
      summary: Complete a delivery to a customer.
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - signature
                - deviceId
                - date
                - creditPayment
                - payments
              properties:
                orderId:
                  type: string
                  description: ID of the order for return pick up.
                deviceId:
                  type: string
                  description: ID of the device being used.
                type:
                  type: string
                  description: Type of the order. One of connect, international, or domestic
                  enum:
                    - connect
                    - international
                    - domestic
      responses:
        '200':
          description: The request was made successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: There was something wrong about how the request was sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    GeoPoint:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the request was successful or not
        data:
          type: object
          description: The data returned, if any
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Description of the error.      
        error:
          type: object
          description: The error object      
    Order:
      type: object
      properties:
        companyEmail:
          type: string
        companyId:
          type: string
        companyName:
          type: string
        companyPhone:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        itemsCount:
          type: integer
        itemsDescription:
          type: string
        customerEmail:
          type: string
        customerId:
          type: string
        customerName:
          type: string
        customerPhone:
          type: string
        deliveryAddress:
          type: object
          properties:
            address:
              type: string
            streetName:
              type: string
            location:
              $ref: '#/components/schemas/GeoPoint'
        deliveryDate:
          type: string
          format: date
        deliveryFee:
          type: number
        deliveryZone:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        driver:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            phone:
              type: string
            username:
              type: string
        driverArrived:
          type: boolean
        driverArrivedAt:
          type: string
          format: date-time
        driverArrivedAtPickup:
          type: boolean
        driverAssignedAt:
          type: string
          format: date-time
        driverEnRoute:
          type: boolean
        driverEstimatedArrivalTime:
          type: string
          format: date-time
          nullable: true
        driverNearby:
          type: boolean
        lastLocationUpdate:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
            lastUpdate:
              type: string
              format: date-time
          nullable: true
        offloadedAt:
          type: string
          format: date-time
        onboardedAt:
          type: string
          format: date-time
        orderNumber:
          type: string
        origin:
          type: string
          enum:
            - csf-connect
            - domestic
            - international
        originalDriverEstimatedArrivalTime:
          type: string
          format: date-time
          nullable: true
        paymentMethod:
          type: string
        paymentOnDeliveryAmount:
          type: number
        pickupAddress:
          type: object
          properties:
            address:
              type: string
            streetName:
              type: string
            location:
              $ref: '#/components/schemas/GeoPoint'
        pickupZone:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        planType:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        sentDeliveryBeginAlert:
          type: boolean
        specialNotes:
          type: string
        tags:
          type: array
          items:
            type: string
        total:
          type: number
        trackingId:
          type: string
        tripId:
          type: string
        tripOrder:
          type: integer
        type:
          type: string
          enum:
            - pickup
            - delivery
            - return
        weight:
          type: number
